use_frameworks!

platform :ios, '10.0'

target 'LDTeamPerformanceTrackerLib_Example' do
  pod 'LDTeamPerformanceTrackerLib', :path => '../'

  target 'LDTeamPerformanceTrackerLib_Tests' do
    inherit! :search_paths

    
  end
end

install! 'cocoapods',
:disable_input_output_paths => true,
:preserve_pod_file_structure => true
